language: cpp

before_install:
 - sudo apt-get update
 - sudo apt-get install tcl-dev #cython python-numpy
 - if [[ x$with_mpi != xfalse ]]; then sudo apt-get install libopenmpi-dev openmpi-bin; fi
 - if [[ x$with_fftw != xfalse ]]; then sudo apt-get install libfftw3-dev; fi

mpi:
  - with_mpi=false
  - with_mpi=true

ffw:
  - with_fftw=false
  - with_fftw=true

env:
  - myconfig=maxset
  - myconfig=default
  - myconfig=molcut
  - myconfig=nocheck-maxset

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - compiler: clang
      mpi: with_mpi=true

script: ./maintainer/travis/build.sh

